### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by kyle1373** [kyle1373/Archiverse#24]
- Spanish: https://docs.google.com/document/d/1Su5VNAKCB8YXti2KYHTQp54mV1HQ8nCwfkizBdNWmvk/edit?usp=sharing
- Japanese: yuta to contact
- Portugese: [GabIsAwesome](https://github.com/GabIsAwesome)

Other languages open as well

**Comment by GabIsAwesome** [comment]
I could translate the website to Brazilian Portuguese!

**Comment by kyle1373** [comment]
> I could translate the website to Brazilian Portuguese!

That would be great! Check out the Spanish document linked in the issue for sections that should be translated to Brazilian Portuguese :) Share it as a Google doc and I'll add it to the site soon!

**Comment by GabIsAwesome** [comment]
I used the Spanish Google Doc as a base to do this, because it already had everything I needed, hope that isn't a problem. Anyways, you can access the doc [here](https://docs.google.com/document/d/1Y5ue3kRVve5HepBGH6CO4ElTMyDhHNV1vK-rV_eJ-8g/edit?usp=sharing). ^^
