### ISSUE TITLE
Implement verified user badge

### ISSUE THREAD

**Issue by GabIsAwesome** [kyle1373/Archiverse#26]
Profiles like https://www.archiverse.app/users/NintendoTom do not show the verified badge when they did in the original Miiverse website.

**Comment by kyle1373** [comment]
Good idea. While the [original archived Miiverse database](https://archive.org/details/archiverse) did not save verified badges, we can definitely do it manually. If you can list verified profiles here, I can implement the verified badge for each of them.

**Comment by GabIsAwesome** [comment]
It's kinda hard for me to list all of them, since these were also distributed to accounts from game developers and relevant accounts.
The most known accounts are some of these, though:
NintendoErika
NintendoTom
NintendoAmy
NintendoAzusa

**Comment by kyle1373** [comment]
Sounds good thanks! What I think I will do is go through all announcement communities in the database and compile a list of NNIDs which are verified.

**Comment by kyle1373** [comment]
Archiverse has been acquired by @PretendoNetwork. Please redirect this issue there: https://github.com/pretendonetwork/archiverse
