### ISSUE TITLE
Add "official posts" view

### ISSUE THREAD

**Issue by mariomadproductions** [kyle1373/Archiverse#37]
Like Miiverse had

**Comment by kyle1373** [comment]
Are you referring to announcement communities? Or verified users?

**Comment by mariomadproductions** [comment]
> Are you referring to announcement communities? Or verified users?

Ah yeah sorry, I meant the "posts by verified users" page.

**Comment by kyle1373** [comment]
Do you mean [this page](https://web.archive.org/web/20170918232728/https://miiverse.nintendo.net/identified_user_posts?view_region_id=5)?

**Comment by mariomadproductions** [comment]
Yeah

**Comment by kyle1373** [comment]
Archiverse has been acquired by @PretendoNetwork. Please redirect this issue there: https://github.com/pretendonetwork/archiverse
